DROP PROCEDURE CREAR_VISTA_USER;                                                                                                                 
DROP PROCEDURE C1_CAPITALIZACION_BURSATIL;                                                                                                                                                                                                                      
DROP PROCEDURE H0_FUNCION_USUARIO_LOGIN;                                                                                                         
DROP PROCEDURE H02_INSERCIONES_BASICAS;                                                                                                          
DROP PROCEDURE H03_CREAR_USUARIOS_ALEATORIO;                                                                                                     
DROP PROCEDURE H04_CREAR_MONEDERO_ALEATORIO;                                                                                                     
DROP PROCEDURE H05_SIMULA_5_MILLON_TRADING;                                                                                                      
DROP PROCEDURE H07_SIMULA_DEPOSI_RETIRO;                                                                                                     
DROP PROCEDURE H08_CREAR_HISTO_MONE_MERCA;                                                                                                       
DROP PROCEDURE H10_SIMULACION_MONTECARLO;                                                                                                        
DROP PROCEDURE H11_SIMULACION_REGRESIONES;                                                                                                       
DROP PROCEDURE H111_REGRESEION_LINEAL;                                                                                                           
DROP PROCEDURE H112_REGRESEION_CUADRATICA;                                                                                                       
DROP PROCEDURE H113_REGRESEION_EXPONENCIAL;                                                                                                      
DROP PROCEDURE H12_OPTIMIZACION_VENTA;                                                                                                           
DROP PROCEDURE H13_GANANCIA_MERCADO_DIA;                                                                                                         
DROP PROCEDURE H14_CORRECION_DE_MERCADO;                                                                                                         
DROP TRIGGER 1.1.COMPRA_VENTA_ID_AUTO;                                                                                                         
DROP TRIGGER 1.2.DEPOSITO_RETIRO_ID_AUTO;                                                                                                      
DROP TRIGGER 1.3.HISTOR_MONE_MER_ID_AUTO;                                                                                                      
DROP TRIGGER 1.4.MERCADO_ID_AUTOINCREMENTO;                                                                                                    
DROP TRIGGER 1.5.MONEDA_ID_AUTOINCREMENTO;                                                                                                     
DROP TRIGGER 1.6.MONEDERO_ID_AUTOINCREMENTO;                                                                                                   
DROP TRIGGER 1.7.USUARIO_ID_AUTO;                                                                                                              
DROP TRIGGER 2.1VERIFICAR_MAYOR_EDAD;                                                                                                          
DROP TRIGGER 2.2CREAR_MONEDERO;                                                                                                                
DROP TRIGGER 3.1.actualizar_contrasenas;                                                                                                       
DROP TRIGGER 3.2.actualizar_monedero;                                                                                                          
DROP TRIGGER 6.TRADING_ACTUALIZA_TRANSAON;                                                                                                     
DROP SEQUENCE SECUENCIA_COMPRA_VENTA_ID;                                                                                                        
DROP SEQUENCE SECUENCIA_DEPOSITO_RETIRO_ID;                                                                                                     
DROP SEQUENCE SECUENCIA_HISTOR_MONE_MER_ID;                                                                                                     
DROP SEQUENCE SECUENCIA_MERCADO_ID;                                                                                                             
DROP SEQUENCE SECUENCIA_MONEDA_ID;                                                                                                              
DROP SEQUENCE SECUENCIA_MONEDERO_ID;                                                                                                            
DROP SEQUENCE SECUENCIA_USUARIO_ID;                                                                                                             
DROP TABLE COMPRA_VENTA CASCADE CONSTRAINTS;                                                                                                    
DROP TABLE DEPOSITO_RETIRO CASCADE CONSTRAINTS;                                                                                                 
DROP TABLE HISTORIAL_COMPRA_VENTA CASCADE CONSTRAINTS;                                                                                          
DROP TABLE HISTORIAL_DEPOSITO_RETIRO CASCADE CONSTRAINTS;                                                                                       
DROP TABLE HISTORIAL_MONEDAS_MERCADO CASCADE CONSTRAINTS;                                                                                       
DROP TABLE MERCADO CASCADE CONSTRAINTS;                                                                                                         
DROP TABLE MONEDA CASCADE CONSTRAINTS;                                                                                                          
DROP TABLE MONEDERO CASCADE CONSTRAINTS;                                                                                                        
DROP TABLE USUARIO CASCADE CONSTRAINTS;    
DROP TYPE CONTRASENAS;
DROP TYPE DATOS_PERSONALES;
DROP TYPE H_MONEDERO;
DROP TYPE MONEDEROS_H;
DROP TYPE TABLAPREDIC;
DROP TYPE PREDICCIONES;
DROP TYPE TELEFONOS;
DROP TYPE UBICACIONES;
DROP VIEW VISTA_USUARIO; 
DROP VIEW VISTA_ADMINISTRADOR;     
DROP VIEW VISTA_MONEDERO;     
DROP VIEW VISTA_ORDENES;     
PURGE RECYCLEBIN; 